// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/machine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMachineRequest) Reset() {
	*x = StartMachineRequest{}
	mi := &file_proto_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMachineRequest) ProtoMessage() {}

func (x *StartMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMachineRequest.ProtoReflect.Descriptor instead.
func (*StartMachineRequest) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{0}
}

func (x *StartMachineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StartMachineRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type StopMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMachineRequest) Reset() {
	*x = StopMachineRequest{}
	mi := &file_proto_machine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMachineRequest) ProtoMessage() {}

func (x *StopMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMachineRequest.ProtoReflect.Descriptor instead.
func (*StopMachineRequest) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{1}
}

func (x *StopMachineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CloneMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldId         string                 `protobuf:"bytes,1,opt,name=old_id,json=oldId,proto3" json:"old_id,omitempty"`
	NewId         string                 `protobuf:"bytes,2,opt,name=new_id,json=newId,proto3" json:"new_id,omitempty"`
	NewHost       string                 `protobuf:"bytes,3,opt,name=new_host,json=newHost,proto3" json:"new_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneMachineRequest) Reset() {
	*x = CloneMachineRequest{}
	mi := &file_proto_machine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneMachineRequest) ProtoMessage() {}

func (x *CloneMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneMachineRequest.ProtoReflect.Descriptor instead.
func (*CloneMachineRequest) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{2}
}

func (x *CloneMachineRequest) GetOldId() string {
	if x != nil {
		return x.OldId
	}
	return ""
}

func (x *CloneMachineRequest) GetNewId() string {
	if x != nil {
		return x.NewId
	}
	return ""
}

func (x *CloneMachineRequest) GetNewHost() string {
	if x != nil {
		return x.NewHost
	}
	return ""
}

type ListMachinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachinesRequest) Reset() {
	*x = ListMachinesRequest{}
	mi := &file_proto_machine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachinesRequest) ProtoMessage() {}

func (x *ListMachinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachinesRequest.ProtoReflect.Descriptor instead.
func (*ListMachinesRequest) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{3}
}

type MachineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Running       bool                   `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`
	Started       string                 `protobuf:"bytes,4,opt,name=started,proto3" json:"started,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineResponse) Reset() {
	*x = MachineResponse{}
	mi := &file_proto_machine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineResponse) ProtoMessage() {}

func (x *MachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineResponse.ProtoReflect.Descriptor instead.
func (*MachineResponse) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{4}
}

func (x *MachineResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MachineResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *MachineResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *MachineResponse) GetStarted() string {
	if x != nil {
		return x.Started
	}
	return ""
}

type StopMachineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopMachineResponse) Reset() {
	*x = StopMachineResponse{}
	mi := &file_proto_machine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopMachineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopMachineResponse) ProtoMessage() {}

func (x *StopMachineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopMachineResponse.ProtoReflect.Descriptor instead.
func (*StopMachineResponse) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{5}
}

func (x *StopMachineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListMachinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machines      []*MachineResponse     `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMachinesResponse) Reset() {
	*x = ListMachinesResponse{}
	mi := &file_proto_machine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMachinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMachinesResponse) ProtoMessage() {}

func (x *ListMachinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_machine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMachinesResponse.ProtoReflect.Descriptor instead.
func (*ListMachinesResponse) Descriptor() ([]byte, []int) {
	return file_proto_machine_proto_rawDescGZIP(), []int{6}
}

func (x *ListMachinesResponse) GetMachines() []*MachineResponse {
	if x != nil {
		return x.Machines
	}
	return nil
}

var File_proto_machine_proto protoreflect.FileDescriptor

const file_proto_machine_proto_rawDesc = "" +
	"\n" +
	"\x13proto/machine.proto\x12\x05proto\"9\n" +
	"\x13StartMachineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\"$\n" +
	"\x12StopMachineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x13CloneMachineRequest\x12\x15\n" +
	"\x06old_id\x18\x01 \x01(\tR\x05oldId\x12\x15\n" +
	"\x06new_id\x18\x02 \x01(\tR\x05newId\x12\x19\n" +
	"\bnew_host\x18\x03 \x01(\tR\anewHost\"\x15\n" +
	"\x13ListMachinesRequest\"i\n" +
	"\x0fMachineResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\x12\x18\n" +
	"\astarted\x18\x04 \x01(\tR\astarted\"/\n" +
	"\x13StopMachineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\x14ListMachinesResponse\x122\n" +
	"\bmachines\x18\x01 \x03(\v2\x16.proto.MachineResponseR\bmachines2\xa7\x02\n" +
	"\x0eMachineService\x12B\n" +
	"\fStartMachine\x12\x1a.proto.StartMachineRequest\x1a\x16.proto.MachineResponse\x12D\n" +
	"\vStopMachine\x12\x19.proto.StopMachineRequest\x1a\x1a.proto.StopMachineResponse\x12B\n" +
	"\fCloneMachine\x12\x1a.proto.CloneMachineRequest\x1a\x16.proto.MachineResponse\x12G\n" +
	"\fListMachines\x12\x1a.proto.ListMachinesRequest\x1a\x1b.proto.ListMachinesResponseB\x16Z\x14micro_machines/protob\x06proto3"

var (
	file_proto_machine_proto_rawDescOnce sync.Once
	file_proto_machine_proto_rawDescData []byte
)

func file_proto_machine_proto_rawDescGZIP() []byte {
	file_proto_machine_proto_rawDescOnce.Do(func() {
		file_proto_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_machine_proto_rawDesc), len(file_proto_machine_proto_rawDesc)))
	})
	return file_proto_machine_proto_rawDescData
}

var file_proto_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_machine_proto_goTypes = []any{
	(*StartMachineRequest)(nil),  // 0: proto.StartMachineRequest
	(*StopMachineRequest)(nil),   // 1: proto.StopMachineRequest
	(*CloneMachineRequest)(nil),  // 2: proto.CloneMachineRequest
	(*ListMachinesRequest)(nil),  // 3: proto.ListMachinesRequest
	(*MachineResponse)(nil),      // 4: proto.MachineResponse
	(*StopMachineResponse)(nil),  // 5: proto.StopMachineResponse
	(*ListMachinesResponse)(nil), // 6: proto.ListMachinesResponse
}
var file_proto_machine_proto_depIdxs = []int32{
	4, // 0: proto.ListMachinesResponse.machines:type_name -> proto.MachineResponse
	0, // 1: proto.MachineService.StartMachine:input_type -> proto.StartMachineRequest
	1, // 2: proto.MachineService.StopMachine:input_type -> proto.StopMachineRequest
	2, // 3: proto.MachineService.CloneMachine:input_type -> proto.CloneMachineRequest
	3, // 4: proto.MachineService.ListMachines:input_type -> proto.ListMachinesRequest
	4, // 5: proto.MachineService.StartMachine:output_type -> proto.MachineResponse
	5, // 6: proto.MachineService.StopMachine:output_type -> proto.StopMachineResponse
	4, // 7: proto.MachineService.CloneMachine:output_type -> proto.MachineResponse
	6, // 8: proto.MachineService.ListMachines:output_type -> proto.ListMachinesResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_machine_proto_init() }
func file_proto_machine_proto_init() {
	if File_proto_machine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_machine_proto_rawDesc), len(file_proto_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_machine_proto_goTypes,
		DependencyIndexes: file_proto_machine_proto_depIdxs,
		MessageInfos:      file_proto_machine_proto_msgTypes,
	}.Build()
	File_proto_machine_proto = out.File
	file_proto_machine_proto_goTypes = nil
	file_proto_machine_proto_depIdxs = nil
}
